config/routes.rb
Rails.application.routes.draw do
  root "pages#homepage"

  devise_for :mentees, path: "mentees", controllers: {
    sessions: "mentees/sessions",
    registrations: "mentees/registrations"
  }

  devise_for :admins, path: "admins", controllers: {
    sessions: "admins/sessions",
    registrations: "admins/registrations"
  }

  devise_for :mentors, path: "mentors", controllers: {
    sessions: "mentors/sessions",
    registrations: "mentors/registrations"
  }

  devise_scope :mentee do
    namespace :mentees do
      get "dashboard", as: :dashboard, to: "dashboard#index"
    end
  end

  devise_scope :mentor do
    namespace :mentors do
      get "dashboard", as: :dashboard, to: "dashboard#index"
    end
  end

  namespace :admins do
    resources :mentors
    resources :mentees
    resources :matches, only: [:index]
    get "dashboard", to: "dashboard#index"
    post "run_match_service", to: "dashboard#run_match_service"
    post "approve_matches", to: "matches#approve_matches"
  end

  resources :meetings
  resources :tasks
  resources :projects
  resources :mentorships
  resources :mentors, only: [:new, :create, :edit, :update] do
    resources :onboarding, only: [:new, :create], controller: "mentor_onboarding"
  end
  resources :mentees, only: [:new, :create, :edit, :update] do
    resources :onboarding, only: [:new, :create], controller: "mentee_onboarding"
  end
  resources :mentor_profiles
  resources :mentee_profiles
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :mentor
  belongs_to :mentee

  validates :title, presence: true
  validates :date_time, presence: true
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: %i[ show edit update destroy ]

  # GET /meetings or /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1 or /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings or /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to meeting_url(@meeting), notice: "Meeting was successfully created." }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1 or /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to meeting_url(@meeting), notice: "Meeting was successfully updated." }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1 or /meetings/1.json
  def destroy
    @meeting.destroy

    respond_to do |format|
      format.html { redirect_to meetings_url, notice: "Meeting was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def meeting_params
      params.require(:meeting).permit(:title, :date_time, :mentor_id, :mentee_id)
    end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<%= form_with(model: meeting) do |form| %>
  <% if meeting.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
        <% meeting.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :date_time, style: "display: block" %>
    <%= form.datetime_field :date_time %>
  </div>

  <div>
    <%= form.label :mentor_id, style: "display: block" %>
    <%= form.text_field :mentor_id %>
  </div>

  <div>
    <%= form.label :mentee_id, style: "display: block" %>
    <%= form.text_field :mentee_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/meetings/_meeting.html.erb
<div id="<%= dom_id meeting %>">
  <p>
    <strong>Title:</strong>
    <%= meeting.title %>
  </p>

  <p>
    <strong>Date time:</strong>
    <%= meeting.date_time %>
  </p>

  <p>
    <strong>Mentor:</strong>
    <%= meeting.mentor_id %>
  </p>

  <p>
    <strong>Mentee:</strong>
    <%= meeting.mentee_id %>
  </p>

</div>

app/views/meetings/edit.html.erb
<h1>Editing meeting</h1>

<%= render "form", meeting: @meeting %>

<br>

<div>
  <%= link_to "Show this meeting", @meeting %> |
  <%= link_to "Back to meetings", meetings_path %>
</div>

app/views/meetings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Meetings</h1>

<div id="meetings">
  <% @meetings.each do |meeting| %>
    <%= render meeting %>
    <p>
      <%= link_to "Show this meeting", meeting %>
    </p>
  <% end %>
</div>

<%= link_to "New meeting", new_meeting_path %>

app/views/meetings/new.html.erb
<h1>New meeting</h1>

<%= render "form", meeting: @meeting %>

<br>

<div>
  <%= link_to "Back to meetings", meetings_path %>
</div>

app/views/meetings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @meeting %>

<div>
  <%= link_to "Edit this meeting", edit_meeting_path(@meeting) %> |
  <%= link_to "Back to meetings", meetings_path %>

  <%= button_to "Destroy this meeting", @meeting, method: :delete %>
</div>