config/routes.rb
Rails.application.routes.draw do
  root "pages#homepage"

  devise_for :mentees, path: "mentees", controllers: {
    sessions: "mentees/sessions",
    registrations: "mentees/registrations"
  }

  devise_for :admins, path: "admins", controllers: {
    sessions: "admins/sessions",
    registrations: "admins/registrations"
  }

  devise_for :mentors, path: "mentors", controllers: {
    sessions: "mentors/sessions",
    registrations: "mentors/registrations"
  }

  devise_scope :mentee do
    namespace :mentees do
      get "dashboard", as: :dashboard, to: "dashboard#index"
    end
  end

  devise_scope :mentor do
    namespace :mentors do
      get "dashboard", as: :dashboard, to: "dashboard#index"
    end
  end

  namespace :admins do
    resources :mentors
    resources :mentees
    resources :matches, only: [:index]
    get "dashboard", to: "dashboard#index"
    post "run_match_service", to: "dashboard#run_match_service"
    post "approve_matches", to: "matches#approve_matches"
  end

  resources :meetings
  resources :tasks
  resources :projects
  resources :mentorships
  resources :mentors, only: [:new, :create, :edit, :update] do
    resources :onboarding, only: [:new, :create], controller: "mentor_onboarding"
  end
  resources :mentees, only: [:new, :create, :edit, :update] do
    resources :onboarding, only: [:new, :create], controller: "mentee_onboarding"
  end
  resources :mentor_profiles
  resources :mentee_profiles
end

app/controllers/admin/matches_controller.rb
class Admin::MatchesController < ApplicationController
  def index
    @matches = session[:matches] ? session[:matches].map { |m| {mentee: Mentee.find(m[:mentee_id]), mentor: Mentor.find(m[:mentor_id])} } : Match.all
  end

  def approve_matches
    if session[:matches]
      session[:matches].each do |match|
        mentor = Mentor.find(match[:mentor_id])
        mentee = Mentee.find(match[:mentee_id])
        Match.create(mentor: mentor, mentee: mentee)
        # Send notifications to mentors and mentees
      end
      session.delete(:matches)
    end
    redirect_to admin_matches_path, notice: "Matches approved and saved!"
  end
end

app/controllers/admins/matches_controller.rb
class Admins::MatchesController < ApplicationController
  before_action :authenticate_admin!
  include Pagy::Backend
  include Filterable

  def index
    query = params[:query]
    filter_params = {query: query}.merge(params.permit(Mentorship::FILTER_PARAMS))
    @pagy, @mentorships = pagy(filter!(:mentorship, filter_params), items: 25)
  end
end

app/helpers/admin/matches_helper.rb
module Admin::MatchesHelper
end

app/views/admin/matches/index.html.erb
<h1>Matches</h1>
<table>
  <thead>
    <tr>
      <th>Mentee</th>
      <th>Mentor</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @matches.each do |match| %>
      <tr>
        <td><%= match[:mentee].name %></td>
        <td><%= match[:mentor].name %></td>
        <td>
          <%= link_to 'Edit', edit_admin_match_path(match[:mentee].id) %> |
          <%= link_to 'Delete', admin_match_path(match[:mentee].id),
            method: :delete,
            data: { confirm: 'Are you sure you want to remove this match?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= button_to 'Approve Matches', admin_approve_matches_path, method: :post %>